#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.454
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DB_13029_randt")]
public partial class AdminDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void InserttblLogonId(tblLogonId instance);
  partial void UpdatetblLogonId(tblLogonId instance);
  partial void DeletetblLogonId(tblLogonId instance);
  #endregion
	
	public AdminDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["DB_13029_randtConnectionString1"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public AdminDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public AdminDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public AdminDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public AdminDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<tblLogonId> tblLogonIds
	{
		get
		{
			return this.GetTable<tblLogonId>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblLogonId")]
public partial class tblLogonId : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _Id;
	
	private string _UserName;
	
	private string _Password;
	
	private System.Nullable<int> _Role;
	
	private System.Nullable<System.DateTime> _LoginDate;
	
	private System.Nullable<bool> _IsAuthenticated;
	
	private string _emailAddress;
	
	private System.Nullable<System.Guid> _newId;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnUserNameChanging(string value);
    partial void OnUserNameChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnRoleChanging(System.Nullable<int> value);
    partial void OnRoleChanged();
    partial void OnLoginDateChanging(System.Nullable<System.DateTime> value);
    partial void OnLoginDateChanged();
    partial void OnIsAuthenticatedChanging(System.Nullable<bool> value);
    partial void OnIsAuthenticatedChanged();
    partial void OnemailAddressChanging(string value);
    partial void OnemailAddressChanged();
    partial void OnnewIdChanging(System.Nullable<System.Guid> value);
    partial void OnnewIdChanged();
    #endregion
	
	public tblLogonId()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int Id
	{
		get
		{
			return this._Id;
		}
		set
		{
			if ((this._Id != value))
			{
				this.OnIdChanging(value);
				this.SendPropertyChanging();
				this._Id = value;
				this.SendPropertyChanged("Id");
				this.OnIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="NVarChar(30)")]
	public string UserName
	{
		get
		{
			return this._UserName;
		}
		set
		{
			if ((this._UserName != value))
			{
				this.OnUserNameChanging(value);
				this.SendPropertyChanging();
				this._UserName = value;
				this.SendPropertyChanged("UserName");
				this.OnUserNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="NVarChar(50)")]
	public string Password
	{
		get
		{
			return this._Password;
		}
		set
		{
			if ((this._Password != value))
			{
				this.OnPasswordChanging(value);
				this.SendPropertyChanging();
				this._Password = value;
				this.SendPropertyChanged("Password");
				this.OnPasswordChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Role", DbType="Int")]
	public System.Nullable<int> Role
	{
		get
		{
			return this._Role;
		}
		set
		{
			if ((this._Role != value))
			{
				this.OnRoleChanging(value);
				this.SendPropertyChanging();
				this._Role = value;
				this.SendPropertyChanged("Role");
				this.OnRoleChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoginDate", DbType="DateTime")]
	public System.Nullable<System.DateTime> LoginDate
	{
		get
		{
			return this._LoginDate;
		}
		set
		{
			if ((this._LoginDate != value))
			{
				this.OnLoginDateChanging(value);
				this.SendPropertyChanging();
				this._LoginDate = value;
				this.SendPropertyChanged("LoginDate");
				this.OnLoginDateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsAuthenticated", DbType="Bit")]
	public System.Nullable<bool> IsAuthenticated
	{
		get
		{
			return this._IsAuthenticated;
		}
		set
		{
			if ((this._IsAuthenticated != value))
			{
				this.OnIsAuthenticatedChanging(value);
				this.SendPropertyChanging();
				this._IsAuthenticated = value;
				this.SendPropertyChanged("IsAuthenticated");
				this.OnIsAuthenticatedChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_emailAddress", DbType="NVarChar(50)")]
	public string emailAddress
	{
		get
		{
			return this._emailAddress;
		}
		set
		{
			if ((this._emailAddress != value))
			{
				this.OnemailAddressChanging(value);
				this.SendPropertyChanging();
				this._emailAddress = value;
				this.SendPropertyChanged("emailAddress");
				this.OnemailAddressChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_newId", DbType="UniqueIdentifier")]
	public System.Nullable<System.Guid> newId
	{
		get
		{
			return this._newId;
		}
		set
		{
			if ((this._newId != value))
			{
				this.OnnewIdChanging(value);
				this.SendPropertyChanging();
				this._newId = value;
				this.SendPropertyChanged("newId");
				this.OnnewIdChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
