#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.488
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DB_13029_randt")]
public partial class ErrorLoggingDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void InsertErrorStack(ErrorStack instance);
  partial void UpdateErrorStack(ErrorStack instance);
  partial void DeleteErrorStack(ErrorStack instance);
  #endregion
	
	public ErrorLoggingDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["DB_13029_randtConnectionString1"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public ErrorLoggingDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public ErrorLoggingDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public ErrorLoggingDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public ErrorLoggingDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<ErrorStack> ErrorStacks
	{
		get
		{
			return this.GetTable<ErrorStack>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ErrorStack")]
public partial class ErrorStack : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _Id;
	
	private System.Nullable<System.DateTime> _CreatedDate;
	
	private string _StackTrace;
	
	private string _RequestorIp;
	
	private System.Nullable<System.Guid> _newId;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnCreatedDateChanging(System.Nullable<System.DateTime> value);
    partial void OnCreatedDateChanged();
    partial void OnStackTraceChanging(string value);
    partial void OnStackTraceChanged();
    partial void OnRequestorIpChanging(string value);
    partial void OnRequestorIpChanged();
    partial void OnnewIdChanging(System.Nullable<System.Guid> value);
    partial void OnnewIdChanged();
    #endregion
	
	public ErrorStack()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int Id
	{
		get
		{
			return this._Id;
		}
		set
		{
			if ((this._Id != value))
			{
				this.OnIdChanging(value);
				this.SendPropertyChanging();
				this._Id = value;
				this.SendPropertyChanged("Id");
				this.OnIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedDate", DbType="DateTime")]
	public System.Nullable<System.DateTime> CreatedDate
	{
		get
		{
			return this._CreatedDate;
		}
		set
		{
			if ((this._CreatedDate != value))
			{
				this.OnCreatedDateChanging(value);
				this.SendPropertyChanging();
				this._CreatedDate = value;
				this.SendPropertyChanged("CreatedDate");
				this.OnCreatedDateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StackTrace", DbType="NVarChar(MAX)")]
	public string StackTrace
	{
		get
		{
			return this._StackTrace;
		}
		set
		{
			if ((this._StackTrace != value))
			{
				this.OnStackTraceChanging(value);
				this.SendPropertyChanging();
				this._StackTrace = value;
				this.SendPropertyChanged("StackTrace");
				this.OnStackTraceChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RequestorIp", DbType="VarChar(50)")]
	public string RequestorIp
	{
		get
		{
			return this._RequestorIp;
		}
		set
		{
			if ((this._RequestorIp != value))
			{
				this.OnRequestorIpChanging(value);
				this.SendPropertyChanging();
				this._RequestorIp = value;
				this.SendPropertyChanged("RequestorIp");
				this.OnRequestorIpChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_newId", DbType="UniqueIdentifier")]
	public System.Nullable<System.Guid> newId
	{
		get
		{
			return this._newId;
		}
		set
		{
			if ((this._newId != value))
			{
				this.OnnewIdChanging(value);
				this.SendPropertyChanging();
				this._newId = value;
				this.SendPropertyChanged("newId");
				this.OnnewIdChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
