#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.454
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DB_13029_randt")]
public partial class LocationsDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void InserttblLocation(tblLocation instance);
  partial void UpdatetblLocation(tblLocation instance);
  partial void DeletetblLocation(tblLocation instance);
  #endregion
	
	public LocationsDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["DB_13029_randtConnectionString1"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public LocationsDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public LocationsDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public LocationsDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public LocationsDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<tblLocation> tblLocations
	{
		get
		{
			return this.GetTable<tblLocation>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblLocations")]
public partial class tblLocation : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _LocId;
	
	private string _LocationName;
	
	private int _UserId;
	
	private System.Nullable<System.Guid> _newId;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnLocIdChanging(int value);
    partial void OnLocIdChanged();
    partial void OnLocationNameChanging(string value);
    partial void OnLocationNameChanged();
    partial void OnUserIdChanging(int value);
    partial void OnUserIdChanged();
    partial void OnnewIdChanging(System.Nullable<System.Guid> value);
    partial void OnnewIdChanged();
    #endregion
	
	public tblLocation()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LocId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int LocId
	{
		get
		{
			return this._LocId;
		}
		set
		{
			if ((this._LocId != value))
			{
				this.OnLocIdChanging(value);
				this.SendPropertyChanging();
				this._LocId = value;
				this.SendPropertyChanged("LocId");
				this.OnLocIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LocationName", DbType="NVarChar(MAX)")]
	public string LocationName
	{
		get
		{
			return this._LocationName;
		}
		set
		{
			if ((this._LocationName != value))
			{
				this.OnLocationNameChanging(value);
				this.SendPropertyChanging();
				this._LocationName = value;
				this.SendPropertyChanged("LocationName");
				this.OnLocationNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserId", DbType="Int NOT NULL")]
	public int UserId
	{
		get
		{
			return this._UserId;
		}
		set
		{
			if ((this._UserId != value))
			{
				this.OnUserIdChanging(value);
				this.SendPropertyChanging();
				this._UserId = value;
				this.SendPropertyChanged("UserId");
				this.OnUserIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_newId", DbType="UniqueIdentifier")]
	public System.Nullable<System.Guid> newId
	{
		get
		{
			return this._newId;
		}
		set
		{
			if ((this._newId != value))
			{
				this.OnnewIdChanging(value);
				this.SendPropertyChanging();
				this._newId = value;
				this.SendPropertyChanged("newId");
				this.OnnewIdChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
