#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.544
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DB_13029_randt")]
public partial class s03_DB_13029_randtDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  #endregion
	
	public s03_DB_13029_randtDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["DB_13029_randtConnectionString1"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public s03_DB_13029_randtDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public s03_DB_13029_randtDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public s03_DB_13029_randtDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public s03_DB_13029_randtDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetAllDBTables")]
	public ISingleResult<GetAllDBTablesResult> GetAllDBTables()
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
		return ((ISingleResult<GetAllDBTablesResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.getCurrentDates")]
	public ISingleResult<getCurrentDatesResult> getCurrentDates([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> today, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> future)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), today, future);
		return ((ISingleResult<getCurrentDatesResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_BackupOnInsert")]
	public void sp_BackupOnInsert()
	{
		this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_CheckIfDuplicates")]
	public ISingleResult<sp_CheckIfDuplicatesResult> sp_CheckIfDuplicates([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> pk, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> cdate, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string loc, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(250)")] string wkDesc, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(18,2)")] System.Nullable<decimal> wkHrs, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Money")] System.Nullable<decimal> expenses, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(250)")] string comment, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> createDate, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> lu)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pk, cdate, loc, wkDesc, wkHrs, expenses, comment, createDate, lu);
		return ((ISingleResult<sp_CheckIfDuplicatesResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_FormatMap")]
	public int sp_FormatMap([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(100)")] string newAddress)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, newAddress);
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_GetName")]
	public ISingleResult<sp_GetNameResult> sp_GetName([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string name)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), name);
		return ((ISingleResult<sp_GetNameResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_Insert")]
	public int sp_Insert([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(30)")] string userId)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), userId);
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_InsertNewRecord")]
	public int sp_InsertNewRecord([global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserId", DbType="Int")] System.Nullable<int> userId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Date", DbType="DateTime")] System.Nullable<System.DateTime> date, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Location", DbType="NVarChar(1)")] string location, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="WorkDescription", DbType="NVarChar(1)")] string workDescription, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="WorkHrs", DbType="Decimal(18,0)")] System.Nullable<decimal> workHrs, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Expenses", DbType="Money")] System.Nullable<decimal> expenses, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Comments", DbType="NVarChar(1)")] string comments, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CreatedDate", DbType="DateTime")] System.Nullable<System.DateTime> createdDate, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="LastUpdated", DbType="DateTime")] System.Nullable<System.DateTime> lastUpdated, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PaymentReceived", DbType="Bit")] System.Nullable<bool> paymentReceived, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NewId", DbType="UniqueIdentifier")] System.Nullable<System.Guid> newId, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(1)")] string pictureUrl)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), userId, date, location, workDescription, workHrs, expenses, comments, createdDate, lastUpdated, paymentReceived, newId, pictureUrl);
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_PopulateName")]
	public ISingleResult<sp_PopulateNameResult> sp_PopulateName()
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
		return ((ISingleResult<sp_PopulateNameResult>)(result.ReturnValue));
	}
}

public partial class GetAllDBTablesResult
{
	
	private string _name;
	
	public GetAllDBTablesResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(128) NOT NULL", CanBeNull=false)]
	public string name
	{
		get
		{
			return this._name;
		}
		set
		{
			if ((this._name != value))
			{
				this._name = value;
			}
		}
	}
}

public partial class getCurrentDatesResult
{
	
	private System.Nullable<System.DateTime> _dates;
	
	private string _Day;
	
	public getCurrentDatesResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dates", DbType="DateTime")]
	public System.Nullable<System.DateTime> dates
	{
		get
		{
			return this._dates;
		}
		set
		{
			if ((this._dates != value))
			{
				this._dates = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Day", DbType="NVarChar(124)")]
	public string Day
	{
		get
		{
			return this._Day;
		}
		set
		{
			if ((this._Day != value))
			{
				this._Day = value;
			}
		}
	}
}

public partial class sp_CheckIfDuplicatesResult
{
	
	private int _Column1;
	
	public sp_CheckIfDuplicatesResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="", Storage="_Column1", DbType="Int NOT NULL")]
	public int Column1
	{
		get
		{
			return this._Column1;
		}
		set
		{
			if ((this._Column1 != value))
			{
				this._Column1 = value;
			}
		}
	}
}

public partial class sp_GetNameResult
{
	
	private int _id;
	
	private string _name;
	
	private string _phone_num;
	
	private string _sec_phone_num;
	
	private string _e_mail;
	
	private string _address;
	
	private System.Nullable<System.DateTime> _last_updated;
	
	private string _newAddress;
	
	public sp_GetNameResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL")]
	public int id
	{
		get
		{
			return this._id;
		}
		set
		{
			if ((this._id != value))
			{
				this._id = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(50)")]
	public string name
	{
		get
		{
			return this._name;
		}
		set
		{
			if ((this._name != value))
			{
				this._name = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phone_num", DbType="NVarChar(15)")]
	public string phone_num
	{
		get
		{
			return this._phone_num;
		}
		set
		{
			if ((this._phone_num != value))
			{
				this._phone_num = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sec_phone_num", DbType="NVarChar(15)")]
	public string sec_phone_num
	{
		get
		{
			return this._sec_phone_num;
		}
		set
		{
			if ((this._sec_phone_num != value))
			{
				this._sec_phone_num = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_e_mail", DbType="NVarChar(50)")]
	public string e_mail
	{
		get
		{
			return this._e_mail;
		}
		set
		{
			if ((this._e_mail != value))
			{
				this._e_mail = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_address", DbType="NVarChar(75)")]
	public string address
	{
		get
		{
			return this._address;
		}
		set
		{
			if ((this._address != value))
			{
				this._address = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_last_updated", DbType="SmallDateTime")]
	public System.Nullable<System.DateTime> last_updated
	{
		get
		{
			return this._last_updated;
		}
		set
		{
			if ((this._last_updated != value))
			{
				this._last_updated = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_newAddress", DbType="NVarChar(100)")]
	public string newAddress
	{
		get
		{
			return this._newAddress;
		}
		set
		{
			if ((this._newAddress != value))
			{
				this._newAddress = value;
			}
		}
	}
}

public partial class sp_PopulateNameResult
{
	
	private string _name;
	
	public sp_PopulateNameResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(50)")]
	public string name
	{
		get
		{
			return this._name;
		}
		set
		{
			if ((this._name != value))
			{
				this._name = value;
			}
		}
	}
}
#pragma warning restore 1591
