#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.488
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DB_13029_randt")]
public partial class TNEDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void InserttblTimeExpensesSummary(tblTimeExpensesSummary instance);
  partial void UpdatetblTimeExpensesSummary(tblTimeExpensesSummary instance);
  partial void DeletetblTimeExpensesSummary(tblTimeExpensesSummary instance);
  partial void InserttblTimeExpensesSummary_history(tblTimeExpensesSummary_history instance);
  partial void UpdatetblTimeExpensesSummary_history(tblTimeExpensesSummary_history instance);
  partial void DeletetblTimeExpensesSummary_history(tblTimeExpensesSummary_history instance);
  #endregion
	
	public TNEDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["DB_13029_randtConnectionString1"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public TNEDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public TNEDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public TNEDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public TNEDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<tblTimeExpensesSummary> tblTimeExpensesSummaries
	{
		get
		{
			return this.GetTable<tblTimeExpensesSummary>();
		}
	}
	
	public System.Data.Linq.Table<tblTimeExpensesSummary_history> tblTimeExpensesSummary_histories
	{
		get
		{
			return this.GetTable<tblTimeExpensesSummary_history>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblTimeExpensesSummary")]
public partial class tblTimeExpensesSummary : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _Id;
	
	private System.Nullable<int> _UserId;
	
	private System.Nullable<System.DateTime> _Date;
	
	private string _Location;
	
	private string _WorkDescription;
	
	private System.Nullable<decimal> _WorkHrs;
	
	private System.Nullable<decimal> _Expenses;
	
	private string _Comments;
	
	private System.Nullable<System.DateTime> _CreatedDate;
	
	private System.Nullable<System.DateTime> _LastUpdated;
	
	private System.Nullable<bool> _PaymentReceived;
	
	private System.Nullable<System.Guid> _NewId;
	
	private string _pictureUrl;
	
	private EntitySet<tblTimeExpensesSummary_history> _tblTimeExpensesSummary_histories;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnUserIdChanging(System.Nullable<int> value);
    partial void OnUserIdChanged();
    partial void OnDateChanging(System.Nullable<System.DateTime> value);
    partial void OnDateChanged();
    partial void OnLocationChanging(string value);
    partial void OnLocationChanged();
    partial void OnWorkDescriptionChanging(string value);
    partial void OnWorkDescriptionChanged();
    partial void OnWorkHrsChanging(System.Nullable<decimal> value);
    partial void OnWorkHrsChanged();
    partial void OnExpensesChanging(System.Nullable<decimal> value);
    partial void OnExpensesChanged();
    partial void OnCommentsChanging(string value);
    partial void OnCommentsChanged();
    partial void OnCreatedDateChanging(System.Nullable<System.DateTime> value);
    partial void OnCreatedDateChanged();
    partial void OnLastUpdatedChanging(System.Nullable<System.DateTime> value);
    partial void OnLastUpdatedChanged();
    partial void OnPaymentReceivedChanging(System.Nullable<bool> value);
    partial void OnPaymentReceivedChanged();
    partial void OnNewIdChanging(System.Nullable<System.Guid> value);
    partial void OnNewIdChanged();
    partial void OnpictureUrlChanging(string value);
    partial void OnpictureUrlChanged();
    #endregion
	
	public tblTimeExpensesSummary()
	{
		this._tblTimeExpensesSummary_histories = new EntitySet<tblTimeExpensesSummary_history>(new Action<tblTimeExpensesSummary_history>(this.attach_tblTimeExpensesSummary_histories), new Action<tblTimeExpensesSummary_history>(this.detach_tblTimeExpensesSummary_histories));
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int Id
	{
		get
		{
			return this._Id;
		}
		set
		{
			if ((this._Id != value))
			{
				this.OnIdChanging(value);
				this.SendPropertyChanging();
				this._Id = value;
				this.SendPropertyChanged("Id");
				this.OnIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserId", DbType="Int")]
	public System.Nullable<int> UserId
	{
		get
		{
			return this._UserId;
		}
		set
		{
			if ((this._UserId != value))
			{
				this.OnUserIdChanging(value);
				this.SendPropertyChanging();
				this._UserId = value;
				this.SendPropertyChanged("UserId");
				this.OnUserIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Date", DbType="DateTime")]
	public System.Nullable<System.DateTime> Date
	{
		get
		{
			return this._Date;
		}
		set
		{
			if ((this._Date != value))
			{
				this.OnDateChanging(value);
				this.SendPropertyChanging();
				this._Date = value;
				this.SendPropertyChanged("Date");
				this.OnDateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Location", DbType="NVarChar(MAX)")]
	public string Location
	{
		get
		{
			return this._Location;
		}
		set
		{
			if ((this._Location != value))
			{
				this.OnLocationChanging(value);
				this.SendPropertyChanging();
				this._Location = value;
				this.SendPropertyChanged("Location");
				this.OnLocationChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WorkDescription", DbType="NVarChar(MAX)")]
	public string WorkDescription
	{
		get
		{
			return this._WorkDescription;
		}
		set
		{
			if ((this._WorkDescription != value))
			{
				this.OnWorkDescriptionChanging(value);
				this.SendPropertyChanging();
				this._WorkDescription = value;
				this.SendPropertyChanged("WorkDescription");
				this.OnWorkDescriptionChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WorkHrs", DbType="Decimal(18,2)")]
	public System.Nullable<decimal> WorkHrs
	{
		get
		{
			return this._WorkHrs;
		}
		set
		{
			if ((this._WorkHrs != value))
			{
				this.OnWorkHrsChanging(value);
				this.SendPropertyChanging();
				this._WorkHrs = value;
				this.SendPropertyChanged("WorkHrs");
				this.OnWorkHrsChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Expenses", DbType="Money")]
	public System.Nullable<decimal> Expenses
	{
		get
		{
			return this._Expenses;
		}
		set
		{
			if ((this._Expenses != value))
			{
				this.OnExpensesChanging(value);
				this.SendPropertyChanging();
				this._Expenses = value;
				this.SendPropertyChanged("Expenses");
				this.OnExpensesChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Comments", DbType="NVarChar(MAX)")]
	public string Comments
	{
		get
		{
			return this._Comments;
		}
		set
		{
			if ((this._Comments != value))
			{
				this.OnCommentsChanging(value);
				this.SendPropertyChanging();
				this._Comments = value;
				this.SendPropertyChanged("Comments");
				this.OnCommentsChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedDate", DbType="DateTime")]
	public System.Nullable<System.DateTime> CreatedDate
	{
		get
		{
			return this._CreatedDate;
		}
		set
		{
			if ((this._CreatedDate != value))
			{
				this.OnCreatedDateChanging(value);
				this.SendPropertyChanging();
				this._CreatedDate = value;
				this.SendPropertyChanged("CreatedDate");
				this.OnCreatedDateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastUpdated", DbType="DateTime")]
	public System.Nullable<System.DateTime> LastUpdated
	{
		get
		{
			return this._LastUpdated;
		}
		set
		{
			if ((this._LastUpdated != value))
			{
				this.OnLastUpdatedChanging(value);
				this.SendPropertyChanging();
				this._LastUpdated = value;
				this.SendPropertyChanged("LastUpdated");
				this.OnLastUpdatedChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PaymentReceived", DbType="Bit")]
	public System.Nullable<bool> PaymentReceived
	{
		get
		{
			return this._PaymentReceived;
		}
		set
		{
			if ((this._PaymentReceived != value))
			{
				this.OnPaymentReceivedChanging(value);
				this.SendPropertyChanging();
				this._PaymentReceived = value;
				this.SendPropertyChanged("PaymentReceived");
				this.OnPaymentReceivedChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NewId", DbType="UniqueIdentifier")]
	public System.Nullable<System.Guid> NewId
	{
		get
		{
			return this._NewId;
		}
		set
		{
			if ((this._NewId != value))
			{
				this.OnNewIdChanging(value);
				this.SendPropertyChanging();
				this._NewId = value;
				this.SendPropertyChanged("NewId");
				this.OnNewIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pictureUrl", DbType="NVarChar(50)")]
	public string pictureUrl
	{
		get
		{
			return this._pictureUrl;
		}
		set
		{
			if ((this._pictureUrl != value))
			{
				this.OnpictureUrlChanging(value);
				this.SendPropertyChanging();
				this._pictureUrl = value;
				this.SendPropertyChanged("pictureUrl");
				this.OnpictureUrlChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblTimeExpensesSummary_tblTimeExpensesSummary_history", Storage="_tblTimeExpensesSummary_histories", ThisKey="Id,UserId,NewId", OtherKey="Id,UserId,NewId")]
	public EntitySet<tblTimeExpensesSummary_history> tblTimeExpensesSummary_histories
	{
		get
		{
			return this._tblTimeExpensesSummary_histories;
		}
		set
		{
			this._tblTimeExpensesSummary_histories.Assign(value);
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_tblTimeExpensesSummary_histories(tblTimeExpensesSummary_history entity)
	{
		this.SendPropertyChanging();
		entity.tblTimeExpensesSummary = this;
	}
	
	private void detach_tblTimeExpensesSummary_histories(tblTimeExpensesSummary_history entity)
	{
		this.SendPropertyChanging();
		entity.tblTimeExpensesSummary = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblTimeExpensesSummary_history")]
public partial class tblTimeExpensesSummary_history : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _Id;
	
	private System.Nullable<int> _UserId;
	
	private System.Nullable<System.DateTime> _Date;
	
	private string _Location;
	
	private string _WorkDescription;
	
	private System.Nullable<decimal> _WorkHrs;
	
	private System.Nullable<decimal> _Expenses;
	
	private string _Comments;
	
	private System.Nullable<System.DateTime> _CreatedDate;
	
	private System.Nullable<System.DateTime> _LastUpdated;
	
	private System.Nullable<bool> _PaymentReceived;
	
	private System.Nullable<System.Guid> _NewId;
	
	private string _pictureUrl;
	
	private EntityRef<tblTimeExpensesSummary> _tblTimeExpensesSummary;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnUserIdChanging(System.Nullable<int> value);
    partial void OnUserIdChanged();
    partial void OnDateChanging(System.Nullable<System.DateTime> value);
    partial void OnDateChanged();
    partial void OnLocationChanging(string value);
    partial void OnLocationChanged();
    partial void OnWorkDescriptionChanging(string value);
    partial void OnWorkDescriptionChanged();
    partial void OnWorkHrsChanging(System.Nullable<decimal> value);
    partial void OnWorkHrsChanged();
    partial void OnExpensesChanging(System.Nullable<decimal> value);
    partial void OnExpensesChanged();
    partial void OnCommentsChanging(string value);
    partial void OnCommentsChanged();
    partial void OnCreatedDateChanging(System.Nullable<System.DateTime> value);
    partial void OnCreatedDateChanged();
    partial void OnLastUpdatedChanging(System.Nullable<System.DateTime> value);
    partial void OnLastUpdatedChanged();
    partial void OnPaymentReceivedChanging(System.Nullable<bool> value);
    partial void OnPaymentReceivedChanged();
    partial void OnNewIdChanging(System.Nullable<System.Guid> value);
    partial void OnNewIdChanged();
    partial void OnpictureUrlChanging(string value);
    partial void OnpictureUrlChanged();
    #endregion
	
	public tblTimeExpensesSummary_history()
	{
		this._tblTimeExpensesSummary = default(EntityRef<tblTimeExpensesSummary>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int Id
	{
		get
		{
			return this._Id;
		}
		set
		{
			if ((this._Id != value))
			{
				if (this._tblTimeExpensesSummary.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnIdChanging(value);
				this.SendPropertyChanging();
				this._Id = value;
				this.SendPropertyChanged("Id");
				this.OnIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserId", DbType="Int")]
	public System.Nullable<int> UserId
	{
		get
		{
			return this._UserId;
		}
		set
		{
			if ((this._UserId != value))
			{
				if (this._tblTimeExpensesSummary.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnUserIdChanging(value);
				this.SendPropertyChanging();
				this._UserId = value;
				this.SendPropertyChanged("UserId");
				this.OnUserIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Date", DbType="DateTime")]
	public System.Nullable<System.DateTime> Date
	{
		get
		{
			return this._Date;
		}
		set
		{
			if ((this._Date != value))
			{
				this.OnDateChanging(value);
				this.SendPropertyChanging();
				this._Date = value;
				this.SendPropertyChanged("Date");
				this.OnDateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Location", DbType="NVarChar(MAX)")]
	public string Location
	{
		get
		{
			return this._Location;
		}
		set
		{
			if ((this._Location != value))
			{
				this.OnLocationChanging(value);
				this.SendPropertyChanging();
				this._Location = value;
				this.SendPropertyChanged("Location");
				this.OnLocationChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WorkDescription", DbType="NVarChar(MAX)")]
	public string WorkDescription
	{
		get
		{
			return this._WorkDescription;
		}
		set
		{
			if ((this._WorkDescription != value))
			{
				this.OnWorkDescriptionChanging(value);
				this.SendPropertyChanging();
				this._WorkDescription = value;
				this.SendPropertyChanged("WorkDescription");
				this.OnWorkDescriptionChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WorkHrs", DbType="Decimal(18,2)")]
	public System.Nullable<decimal> WorkHrs
	{
		get
		{
			return this._WorkHrs;
		}
		set
		{
			if ((this._WorkHrs != value))
			{
				this.OnWorkHrsChanging(value);
				this.SendPropertyChanging();
				this._WorkHrs = value;
				this.SendPropertyChanged("WorkHrs");
				this.OnWorkHrsChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Expenses", DbType="Money")]
	public System.Nullable<decimal> Expenses
	{
		get
		{
			return this._Expenses;
		}
		set
		{
			if ((this._Expenses != value))
			{
				this.OnExpensesChanging(value);
				this.SendPropertyChanging();
				this._Expenses = value;
				this.SendPropertyChanged("Expenses");
				this.OnExpensesChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Comments", DbType="NVarChar(MAX)")]
	public string Comments
	{
		get
		{
			return this._Comments;
		}
		set
		{
			if ((this._Comments != value))
			{
				this.OnCommentsChanging(value);
				this.SendPropertyChanging();
				this._Comments = value;
				this.SendPropertyChanged("Comments");
				this.OnCommentsChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedDate", DbType="DateTime")]
	public System.Nullable<System.DateTime> CreatedDate
	{
		get
		{
			return this._CreatedDate;
		}
		set
		{
			if ((this._CreatedDate != value))
			{
				this.OnCreatedDateChanging(value);
				this.SendPropertyChanging();
				this._CreatedDate = value;
				this.SendPropertyChanged("CreatedDate");
				this.OnCreatedDateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastUpdated", DbType="DateTime")]
	public System.Nullable<System.DateTime> LastUpdated
	{
		get
		{
			return this._LastUpdated;
		}
		set
		{
			if ((this._LastUpdated != value))
			{
				this.OnLastUpdatedChanging(value);
				this.SendPropertyChanging();
				this._LastUpdated = value;
				this.SendPropertyChanged("LastUpdated");
				this.OnLastUpdatedChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PaymentReceived", DbType="Bit")]
	public System.Nullable<bool> PaymentReceived
	{
		get
		{
			return this._PaymentReceived;
		}
		set
		{
			if ((this._PaymentReceived != value))
			{
				this.OnPaymentReceivedChanging(value);
				this.SendPropertyChanging();
				this._PaymentReceived = value;
				this.SendPropertyChanged("PaymentReceived");
				this.OnPaymentReceivedChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NewId", DbType="UniqueIdentifier")]
	public System.Nullable<System.Guid> NewId
	{
		get
		{
			return this._NewId;
		}
		set
		{
			if ((this._NewId != value))
			{
				if (this._tblTimeExpensesSummary.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnNewIdChanging(value);
				this.SendPropertyChanging();
				this._NewId = value;
				this.SendPropertyChanged("NewId");
				this.OnNewIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pictureUrl", DbType="NVarChar(50)")]
	public string pictureUrl
	{
		get
		{
			return this._pictureUrl;
		}
		set
		{
			if ((this._pictureUrl != value))
			{
				this.OnpictureUrlChanging(value);
				this.SendPropertyChanging();
				this._pictureUrl = value;
				this.SendPropertyChanged("pictureUrl");
				this.OnpictureUrlChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblTimeExpensesSummary_tblTimeExpensesSummary_history", Storage="_tblTimeExpensesSummary", ThisKey="Id,UserId,NewId", OtherKey="Id,UserId,NewId", IsForeignKey=true)]
	public tblTimeExpensesSummary tblTimeExpensesSummary
	{
		get
		{
			return this._tblTimeExpensesSummary.Entity;
		}
		set
		{
			tblTimeExpensesSummary previousValue = this._tblTimeExpensesSummary.Entity;
			if (((previousValue != value) 
						|| (this._tblTimeExpensesSummary.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._tblTimeExpensesSummary.Entity = null;
					previousValue.tblTimeExpensesSummary_histories.Remove(this);
				}
				this._tblTimeExpensesSummary.Entity = value;
				if ((value != null))
				{
					value.tblTimeExpensesSummary_histories.Add(this);
					this._Id = value.Id;
					this._UserId = value.UserId;
					this._NewId = value.NewId;
				}
				else
				{
					this._Id = default(int);
					this._UserId = default(Nullable<int>);
					this._NewId = default(Nullable<System.Guid>);
				}
				this.SendPropertyChanged("tblTimeExpensesSummary");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
