<?xml version="1.0" encoding="utf-8"?><Database Name="DB_13029_randt" Class="WorkDescDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=s03.winhost.com;Initial Catalog=DB_13029_randt;Persist Security Info=True;User ID=DB_13029_randt_user" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="DB_13029_randtConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.tblWorkDescriptions" Member="tblWorkDescriptions">
    <Type Name="tblWorkDescription">
      <Column Name="WkDescId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="WorkDescription" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="newId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
    </Type>
  </Table>
</Database>